# Generated by Django 3.0 on 2022-05-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220428_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='main_app.Take'),
        ),
    ]
