# Generated by Django 3.0 on 2022-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='takes',
            field=models.ManyToManyField(to='main_app.Take'),
        ),
    ]
